### PR TITLE
Update method name from update to add prefix

### PR DESCRIPTION
**Pull request by chao-xian**
This method only adds orgs to MouSignatures that don't have one. The name mislead me before.

### Things to consider when reviewing

- Ensure that you consider the wider context.
- Does it work when run on your machine?
- Is it clear what the code is doing?
- Do the commit messages explain why the changes were made?
- Are there all the unit tests needed?
- Has all relevant documentation been updated?

### CODE REVIEW

**Review by DavidBiddle — APPROVED** [review]
Seems reaasonable to me, but might benefit from a @alphagov/forms-feature-team-1 dev taking a look

**Comment by chao-xian** [comment]
Thanks @DavidBiddle! Don't want to merge this before having your thoughts @thomasiles

**Comment by aliuk2012** [comment]
🤔  a bit odd that you could rename the method and no tests fail.

**Comment by aliuk2012** [comment]
@chao-xian @thomasiles this method name has changed since this PR but could I propose an alternative way we could have implemented this? 

af086136e3397f4e9cdb2356f8bcaac0ebca1acb

**Comment by chao-xian** [comment]
The spirit of my PR which was to rename I think has been resolved elsewhere so I'll close this PR and let any relevant discussion continue in Al's refactoring PR.

**Pull request closed without merging**
