### PR TITLE
[DO NOT MERGE BEFORE MON 19 FEB] Update crown logo

### PR DESCRIPTION
**Pull request by thomasiles**
### Prepare to update to the new tudor crown

Trello card: https://trello.com/c/D6sa7ptF/1355-deadline-afternoon-on-19th-feb-placeholder-switch-to-tudor-crown-logo

This PR should not be merged until a date has been agreed - see the trello ticket for details.

This PR updates govuk frontend to 5.1.0 which contains new assets for the tudor crown.

https://github.com/alphagov/govuk-frontend/blob/main/CHANGELOG.md#510-feature-release

The current header:
image

The header in this PR:
image

The changes to the manifest icons can be seen in the diff.

This PR uses github references to include unrelased changes of the govuk-components and govuk_design_system_formbuilder. Ideally these would be released and the Gemfile can be updated.

## The image we use on Auth0 is changed

Current:
image

New:
image

The crown image we use on auth0 in the above image comes from https://github.com/alphagov/govuk-frontend/blob/v4.7.0/src/govuk/assets/images/govuk-mask-icon.svg . This file has been updated with the new crown but now uses a black background and transparent crown. This will change the look of the auth screen.

We could change this by modifying the SVG and setting the path as below, should we though?

```svg
<path d="m 415.76 238.55 c 11.12 -4.56 24.05 0.88 28.67 12.11 c 4.63 11.17 -0.72 24.05 -11.85 28.61 c -11.34 4.68 -24.21 -0.67 -28.83 -11.88 c -4.65 -11.18 0.67 -24.18 12.01 -28.84 z m -39.05 -58.11 c 11.12 -4.56 24.05 0.89 28.68 12.12 c 4.62 11.17 -0.73 24.04 -11.85 28.6 c -11.34 4.68 -24.21 -0.67 -28.83 -11.88 c -4.65 -11.18 0.67 -24.18 12 -28.84 z m -58.98 -35.19 c 11.12 -4.57 24.05 0.88 28.67 12.11 c 4.62 11.17 -0.72 24.04 -11.85 28.6 c -11.34 4.68 -24.21 -0.67 -28.84 -11.88 c -4.64 -11.18 0.67 -24.18 12.01 -28.83 z m -101.34 -55.92 l 27.83 8.81 l 0.09 -0.08 c 0.77 -1.03 1.68 -1.94 2.7 -2.73 l 0.08 -0.08 l -11.2 -35.25 h 20.12 s 20.12 0 20.12 0 l -11.2 35.25 l 0.08 0.08 c 1.02 0.79 1.93 1.7 2.7 2.73 l 0.08 0.08 l 27.84 -8.81 v 41.08 l -27.87 -14.63 l -0.06 0.06 c -0.83 1.08 -1.8 2.04 -2.88 2.86 l 16 48.28 c 0.02 0.06 0.05 0.12 0.06 0.18 l 0.02 0.05 c 0.74 2.42 1.14 4.98 1.14 7.63 c 0 13.06 -9.65 23.85 -22.19 25.7 c -0.18 0.03 -0.37 0.06 -0.55 0.08 c -1.07 0.14 -2.16 0.23 -3.26 0.23 c -1.11 0 -2.19 -0.09 -3.26 -0.23 c -0.19 -0.02 -0.38 -0.06 -0.56 -0.08 c -12.55 -1.85 -22.19 -12.63 -22.19 -25.7 c 0 -2.65 0.4 -5.21 1.15 -7.62 s 0.01 -0.06 0.01 -0.06 c 0.02 -0.06 0.04 -0.12 0.06 -0.18 l 16.01 -48.28 c -1.09 -0.81 -2.06 -1.77 -2.88 -2.86 l -0.06 -0.06 l -27.87 14.63 v -41.08 z m 48.11 174.62 c -11.34 4.68 -24.21 -0.67 -28.84 -11.88 c -4.64 -11.18 0.67 -24.18 12.01 -28.83 c 11.12 -4.57 24.05 0.88 28.67 12.11 c 4.62 11.17 -0.72 24.04 -11.85 28.6 z m -99.28 -106.59 c 4.62 -11.23 17.55 -16.68 28.67 -12.11 c 11.34 4.65 16.65 17.65 12.01 28.83 c -4.62 11.21 -17.49 16.56 -28.84 11.88 c -11.12 -4.56 -16.47 -17.44 -11.85 -28.6 z m -58.99 35.2 c 4.63 -11.22 17.55 -16.68 28.68 -12.12 c 11.34 4.65 16.65 17.65 12 28.84 c -4.62 11.21 -17.49 16.56 -28.83 11.88 c -11.12 -4.56 -16.48 -17.44 -11.85 -28.6 z m -39.04 58.11 c 4.62 -11.23 17.55 -16.68 28.67 -12.11 c 11.34 4.65 16.66 17.65 12.01 28.84 c -4.62 11.21 -17.49 16.56 -28.83 11.88 c -11.13 -4.55 -16.47 -17.43 -11.85 -28.61 z m 335.98 169.34 c -44.5 -6.37 -94.44 -9.94 -147.21 -9.94 s -102.66 3.57 -147.14 9.93 c -12.63 -53.1 -28 -83.53 -43.87 -105.19 l 29.89 -10.64 c -2.97 15.18 -3.45 22.24 -0.12 32 c 4.93 -4.82 9.6 -13.68 13.25 -27.23 l 14.49 48.23 c -8.82 -6.07 -15.61 -9.99 -23.39 -10.17 c 13.79 29.7 31.01 37.34 42.17 35.28 c 13.62 -2.5 19.89 -14.65 17.78 -24.95 c -3.13 -14.6 -18.12 -18.41 -25.12 -1.42 c -13.39 -27.31 9.32 -35.81 23.93 -27.73 c -22.44 -22.39 -25.01 -42.29 -6.89 -66.38 c 25.24 19.3 25.54 38.41 14.18 65.3 c 14.74 -16.87 37.68 -7.81 29.4 19.45 c -10.64 -16.46 -24.71 -6.1 -22.5 9.53 c 1.87 13.62 19.85 24.62 42.25 22.68 c 32.1 -2.91 34.01 -25.06 34.81 -43.39 c -7.89 -1.46 -22.1 5.86 -34.22 22.87 l -4.46 -51.16 c 13.18 13.74 25.16 16.35 38.46 16.77 c -4.43 -13.82 -24.78 -36.46 -24.78 -36.46 h 63.85 s -20.35 22.64 -24.78 36.46 c 13.3 -0.42 25.28 -3.03 38.46 -16.77 l -4.46 51.16 c -12.11 -17.01 -26.32 -24.33 -34.21 -22.87 c 0.8 18.34 2.71 40.48 34.81 43.39 c 22.39 1.95 40.38 -9.05 42.25 -22.68 c 2.21 -15.63 -11.86 -25.99 -22.49 -9.53 c -8.29 -27.26 14.65 -36.32 29.39 -19.45 c -11.36 -26.89 -11.07 -46 14.18 -65.3 c 18.12 24.08 15.55 43.99 -6.9 66.38 c 14.62 -8.08 37.32 0.43 23.94 27.73 c -7 -16.99 -21.98 -13.18 -25.12 1.42 c -2.11 10.3 4.15 22.46 17.77 24.95 c 11.16 2.06 28.38 -5.58 42.17 -35.28 c -7.77 0.18 -14.57 4.11 -23.38 10.17 l 14.48 -48.23 c 3.65 13.55 8.32 22.41 13.25 27.23 c 3.33 -9.76 2.85 -16.82 -0.12 -32 l 29.89 10.64 c -15.88 21.66 -31.25 52.09 -43.88 105.2 z"/>

```

### CODE REVIEW

**Review by DavidBiddle — APPROVED** [review]
Interesting - looks like I didn't remember to copy the public icons in this repo when I did it in the others. 
I'll make a separate PR for that - if it gets merged before this one I'll update this one with the new icons.

**Comment by lfdebrux** [comment]
> This file has been updated with the new crown but now uses a black background and transparent crown. This will change the look of the auth screen.

@hazalarpalikli any thoughts on this?

**Comment by DavidBiddle** [comment]
@thomasiles would you mind if I rebased this onto main and updated the icons to match #944 ?

**Review by chao-xian — DISMISSED** [review]

**Review by chao-xian — APPROVED** [review]

**Comment by hazalarpalikli** [comment]
The header looks strange now with the new logo i assume design systems looked into this? about the png image on auth0 it'd be best if we keep the vector black and the background colour white. I saw @chao-xian created a card for it @lfdebrux. Apart from these it looks good to me

**Comment by chao-xian** [comment]
@hazalarpalikli the crown logo's alignment change is as the component is on the Design System https://design-system.service.gov.uk/components/header/

**Pull request merged**
