### PR TITLE
Frontend build setup

### PR DESCRIPTION
**Pull request by DavidBiddle**
Implements #3

### CODE REVIEW

**Review by danielburnley — APPROVED** [review]
Looks good to me 🎉

**Review by 0atman — APPROVED** [review]
Nice :ok_hand:

**Comment by danielburnley** [comment]
Hm - Actually having just used this for the deploy, we'll need the `rails assets:precompile` command to work. As far as I can tell if you're not using import maps (which we're not) you'll need to use Yarn rather than NPM which means we'll want a `yarn.lock` instead of `package-lock.json` i think? (i'm rusty on this 😅 )

**Comment by DavidBiddle** [comment]
The issue with `assets:precompile` should now be fixed 🤞

**Review by danielburnley — APPROVED** [review]
Looks good to me 🎉

**Pull request merged**
